version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-7-openjdk-amd64"

phases:
  install:
    commands:
      - echo Nothing to install
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
